### ISSUE TITLE
No resource or method named `declared_type=' for `Chef::Resource::AutomasterEntry ""'

### ISSUE THREAD

**Issue by HeikoBornholdt** [sous-chefs/autofs#13]
Hi,
I'm trying to use your cookbook. I've added this line of code:

``` ruby
automaster_entry '/misc', '/etc/auto.misc'
```

Now I'm getting the following error:

```
Starting Chef Client, version 12.0.1
Compiling Cookbooks...
Added /root/chef-solo/cookbooks-2/resource/files/lib
[2015-05-16T18:16:58+02:00] WARN: Cloning resource attributes for package[build-essential] from prior resource (CHEF-3694)
[2015-05-16T18:16:58+02:00] WARN: Previous package[build-essential]: /root/chef-solo/cookbooks-3/heiko/recipes/skalibs.rb:18:in `block in from_file'
[2015-05-16T18:16:58+02:00] WARN: Current  package[build-essential]: /root/chef-solo/cookbooks-3/heiko/recipes/hosting.rb:16:in `block in from_file'

================================================================================
Recipe Compile Error in /root/chef-solo/cookbooks-3/heiko/recipes/hosting.rb
================================================================================

NoMethodError
-------------
No resource or method named `declared_type=' for `Chef::Resource::AutomasterEntry ""'

Cookbook Trace:
---------------
  /root/chef-solo/cookbooks-2/resource/files/lib/chef_resource/chef_dsl/chef_recipe_dsl_extensions.rb:62:in `buildbuild_resource_v2'
  /root/chef-solo/cookbooks-2/resource/files/lib/chef_resource/chef_dsl/chef_recipe_dsl_extensions.rb:53:in `build_resource'
  /root/chef-solo/cookbooks-2/resource/files/lib/chef_resource/chef_dsl/resource_container_module.rb:66:in `automaster_entry'
  /root/chef-solo/cookbooks-3/heiko/recipes/hosting_autofs.rb:9:in `from_file'
  /root/chef-solo/cookbooks-3/heiko/recipes/hosting.rb:25:in `from_file'

Relevant File Content:
----------------------
/root/chef-solo/cookbooks-2/resource/files/lib/chef_resource/chef_dsl/chef_recipe_dsl_extensions.rb:

 55:
 56:        def buildbuild_resource_v2(resource_class, *identity, created_at, &update_block)
 57:          resource = resource_class.open(*identity)
 58:          resource.run_context = run_context
 59:          resource.cookbook_name = cookbook_name
 60:          resource.recipe_name = recipe_name
 61:          resource.source_line = created_at
 62>>         resource.declared_type = resource_class.dsl_name
 63:          # Determine whether this resource is being created in the context of an enclosing Provider
 64:          resource.enclosing_provider = self.is_a?(Chef::Provider) ? self : nil
 65:          resource.params = @params
 66:
 67:          # Evaluate resource attribute DSL
 68:          resource.instance_eval(&update_block) if block_given?
 69:
 70:          # Freeze resource
 71:          resource.resource_fully_defined


Running handlers:
[2015-05-16T18:16:58+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-16T18:16:58+02:00] ERROR: Exception handlers complete
[2015-05-16T18:16:58+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.416725405 seconds
[2015-05-16T18:16:58+02:00] ERROR: No resource or method named `declared_type=' for `Chef::Resource::AutomasterEntry ""'
[2015-05-16T18:16:58+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

**Comment by damacus** [comment]
Hi! 

Sadly, even if you're not specifying any extra master options you still need to word the resource as below otherwise it doesn't recognise it as a resource:

```
automaster_entry '/misc', '/etc/auto.misc' do
end
```

**Comment by HeikoBornholdt** [comment]
Thanks for the fast response. This error even occurs when I use the example from your README.md. Have you another idea what causes this problem?

**Comment by damacus** [comment]
Did you add do and end to tour statement?

**Comment by HeikoBornholdt** [comment]
Yes, just like in the readme. I've also tried

```
automaster_entry '/misc', '/etc/auto.misc' do
end
```

**Comment by damacus** [comment]
How does your cookbook differ from the test cookbook under `test/fixtures/cookbooks/auto_master` ?

Including the metadata and recipe stuff. Past that feel free to jump on gitter and I'll be able to run you through some more troubleshooting steps in more real time.

**Comment by HeikoBornholdt** [comment]
I figured out what is causing the error: I was running version 12.0.1 of the chef gem. After upgrade to version 12.0.3 the error is no longer appearing :) .

I suggest to add this as a new dependency to your Gemfile.

Thank you for your help so far.

**Comment by damacus** [comment]
Excellent! Thanks for helping with this bug I'll put it in the
requirements,
